DATASETS: ''
DATASETS_ALL:
- AID
- CLRS
- EuroSAT_RGB
- MLRSNet
- NWPU-RESISC45
- Optimal-31
- PatternNet
- RS_C11
- RSD46-WHU
- RSI-CB128
- RSSCN7
- SAT-4
- SIRI-WHU
- UC_Merced
- WHU-RS19
DATASETS_VAL: ''
batch_size: 32
cache_dir: null
data_location: ./datasets
device: cuda
initialize_sigma: tsvm
model: ViT-B-32
model_location: ./models/checkpoints_remote_sensing
n_eval_points: 31
num_tasks: 15
sigma_epochs: null
sigma_lr: 1.0e-03
sigma_wd: 0.0
sigma_lr_step_size: 1
sigma_lr_gamma: 1.0
train_k: 0
num_grad_accumulation: 1
adapter: none
adapter_lr: null
adapter_wd: null
config_tag: null
epochs_per_task: 10
port: 12355
svd_keep_topk: 5
world_size: 1
blockwise_coef: true
seed: 1
