DATASETS: ''
DATASETS_ALL:
- AID
- CLRS
- EuroSAT_RGB
- MLRSNet
- NWPU-RESISC45
- Optimal-31
- PatternNet
- RS_C11
- RSD46-WHU
- RSI-CB128
- RSSCN7
- SAT-4
- SIRI-WHU
- UC_Merced
- WHU-RS19
DATASETS_VAL: ''
batch_size: 128
cache_dir: None
data_location: ./datasets
device: cuda
initialize_sigma: tsvm
model: ViT-B-32
model_location: ./models/checkpoints_remote_sensing
n_eval_points: 31
num_tasks: 15
port: 12355
svd_keep_topk: 4
world_size: 1
